services:
  postgres:
    image: postgres:latest
    container_name: spm_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Singapore
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d spm"]
    profiles:
      - dev

  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    command: >
      uvicorn backend.main:app
      --host 0.0.0.0 --port 8080 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
    env_file:
      - .env
    image: backend_api
    container_name: backend_api
    depends_on:
      postgres:
        condition: service_healthy
        required: false
    profiles:
      - dev
      - prod

  backend_ci:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    command: >
      uvicorn backend.main:app
      --host 0.0.0.0 --port 8080 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
    image: backend_api_ci
    container_name: backend_api_ci
    profiles:
      - ci

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - dev
volumes:
  pgadmin-data:
